FROM registry.cn-hongkong.aliyuncs.com/stevennight-test/alpine-php-8.3.9-swow

COPY ./etc /opt/etc

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini" \
        && apk add pkgconfig gcc g++ make autoconf linux-headers \
        # install xdebug(dev)
        && pecl install xdebug-3.3.2 \
        && docker-php-ext-enable xdebug \
        && apk del pkgconfig gcc g++ make autoconf linux-headers \
        && cp /opt/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        # clean
        && rm -rf /var/cache/apk/* \
        && rm -rf /tmp/* \
        && rm -rf /opt/etc

ENV XDEBUG_CLIENT_HOST 127.0.0.1